#!/bin/sh

export basedir=$PWD

#Number of topics (taken from command line)
if [ "$1" ];then
    k=$1
fi
#Number of docs (taken from command line)
if [ "$2" ];then
    n=$2
fi
#Vocab size (taken from command line)
if [ "$3" ];then
    m=$3
fi
#Alpha (percentage of points to encapsulate)
a=1 
#Beta (resize parameter)
b=1

#run matlab program
matlab -nodesktop -nosplash -nojvm <<-EOF
cd projector;
ticID = tic;
G = predictTopics('data/documents', $n, $m, $k, 0.9, 1);
elapsedSeconds = toc(ticID);
elapsedTimeFile = fopen('data/projector_elapsed_seconds', 'w');
fprintf(elapsedTimeFile, '%f\n', elapsedSeconds);
fclose(elapsedTimeFile);
exit
EOF
