#!/bin/sh

export basedir=$PWD

#Generator
generator="ctm"
#Number of topics
klist=(30)
#Number of docs
nlist=(50)
#Number of words per document
llist=(30)
#Vocab size
mlist=(500)
#Alpha
alist=(0.001 0.01 0.05)
#Beta
blist=(0.001 0.01 0.05)
#Flag for plotting output
plot=false
#Flag for making table
table=false

while getopts “hk:n:l:m:a:b:gp” OPTION
do
    case $OPTION in
        h)
            echo "Usage: ./run-batch [-h] [-p] [-g]"
            echo "Optional arguments:"
            echo "-h Show this help screen"
            echo "-p Plot all experiment*.json files in data"
            echo "-g Make an HTML table with the data"
            echo "To change the data generation parameters, edit run-batch"
            exit 1
            ;;
        k)
            klist=$OPTARG
            ;;
        n)
            nlist=$OPTARG
            ;;
        l)
            llist=$OPTARG
            ;;
        m)
            mlist=$OPTARG
            ;;
        a)
            alist=$OPTARG
            ;;
        b)
            blist=$OPTARG
            ;;
        g)
            table=true
            ;;
        p)
            plot=true
            ;;
    esac
done

# compile using ant
ant -f build.xml || exit

#Iterate through every combination of parameters
for k in "${klist[@]}";
do
    for n in "${nlist[@]}";
    do
        for l in "${llist[@]}";
        do
            for m in "${mlist[@]}";
            do
                for a in "${alist[@]}";
                do
                    for b in "${blist[@]}";
                    do
                        cd src/datageneration/
                        case "$generator" in
                        hlda)
                            #Generate a data file with given parameters
                            python hlda_journal.py -w -n $n -l $l -m $m -b $b
                            cd $basedir

                            #Make a JSON out of the generated data
                            java -classpath bin:lib/jars/json.jar \
                            datageneration/MakeJSON hldaj-documents-out false

                            #Run the test
                            ./test data/hldaj-documents-out.json $generator $k
                            ;;
                        lda)
                            #Generate a data file with given parameters
                            python documents.py -w -k $k -n $n -l $l -m $m -a $a \
                            -b $b
                            cd $basedir

                            #Make a JSON out of the generated data
                            java -classpath bin:lib/jars/json.jar \
                            datageneration/MakeJSON documents-out $generator

                            #Run the test
                            ./test data/documents-out.json $generator $k
                            ;;
                        ctm)
                            #Generate a data file with given parameters
                            python documents.py -w -k $k -n $n -l $l -m $m -a $a \
                            -b $b -ctm
                            cd $basedir

                            #Make a JSON out of the generated data
                            java -classpath bin:lib/jars/json.jar \
                            datageneration/MakeJSON documents-out $generator

                            #Run the test
                            ./test data/documents-out.json $generator $k
                            ;;
                        esac
                    done
                done
            done
        done
    done
done

if $table; then
    cd $basedir
    python parse_batch.py data
fi

if $plot; then
    cd $basedir
    for f in data/experiment*.json;
    do
        python parse_output.py $f
    done
fi
