#!/bin/sh

export basedir=$PWD

#Number of topics
klist=(15 30 50 75 100)
#Datasets to use
#datalist=("cacm.json" "cisi.json" "cran.json" "med.json" "kos.json" "nips.json")
datalist=("stackoverflow.json")
#datalist=("lastfmsubset.json")
#Flag to make html table
table=false

#Iterate through every combination of parameters
for k in "${klist[@]}";
do
    for d in "${datalist[@]}";
    do
        #Run the test
        ./test data/$d "" $k
    done
done

if $table; then
    cd $basedir
    python parse_batch.py data
fi
