#!/bin/sh

export basedir=$PWD

# compile lda code
cd lib/lda-c-dist; make || exit

# compile using ant
cd $basedir; ant -f build.xml || exit

data=""
if [ "$1" ];then
    data=$1
else
    echo "Please specify an input data file."
fi
[ "$data" ] || exit 1

#takes in name of generator for synthetic data
generator=""
if [ "$2" ];then
    generator=$2
fi

numTopics=15
if [ "$3" ];then
    numTopics=$3
fi

out_dir=.
if [ "$4" ];then
    out_dir=$4
fi

ldaTrain=false
case "$generator" in
lda)
    ldaTrain=true
    ;;
esac

#mkdir $out_dir || exit
echo Output will go in data

args=\
"-Dplusone.dataFile=$data
 -Dplusone.crossValidation.FOLD=10
 -Dplusone.crossValidation.run=false
 -Dplusone.testWordPercents=0.3
 -Dplusone.trainPercents=0.5
 -Dplusone.generator=$generator
 -Dplusone.kValues=3
 -Dplusone.closestKValues=5,15,25
 -Dplusone.closestKSVDishValues=5,10,25,50,100,250,500
 -Dplusone.svdDimensions=$numTopics
 -Dplusone.plsi.dimensions=$numTopics
 -Dplusone.dtrw.walkLength=1
 -Dplusone.dtrw.stoch=true
 -Dplusone.dtrw.nSampleWalks=100
 -Dplusone.dtrw.normalizeDocsInWord=true
 -Dplusone.dtrw.normalizeWordsInDoc=true
 -Dplusone.svdishknn.nLevels=3
 -Dplusone.svdishknn.docEnzs=20,60,120
 -Dplusone.svdishknn.termEnzs=40,120,240
 -Dplusone.svdishknn.dtNs=10,20,50
 -Dplusone.svdishknn.tdNs=10,20,50
 -Dplusone.svdishknn.numLVecs=800,400,200
 -Dplusone.svdishknn.walkLength=3
 -Dplusone.localCO.docEnzs=1500
 -Dplusone.localCO.termEnzs=15000
 -Dplusone.localCO.dtNs=500
 -Dplusone.localCO.tdNs=1200
 -Dplusone.lda.dimensions=$numTopics
 -Dplusone.mallet.gibbsIterations=2000
 -Dplusone.poissonLda.numIterations=100,1000
 -Dplusone.documentLengthRate=75
 -Dplusone.topicAlpha=0.1
 -Dplusone.enableTest.localCO=false
 -Dplusone.enableTest.lda=true
 -Dplusone.enableTest.ldaTrained=$ldaTrain
 -Dplusone.enableTest.ldaCheat=$ldaTrain
 -Dplusone.enableTest.malletLda=true
 -Dplusone.enableTest.malletHlda=false
 -Dplusone.enableTest.projector=true
 -Dplusone.enableTest.hlda=false
 -Dplusone.enableTest.ctm=false
 -Dplusone.enableTest.gibbsLda=false
 -Dplusone.enableTest.knnc=false
 -Dplusone.enableTest.knn=true
 -Dplusone.enableTest.knnrw=false
 -Dplusone.enableTest.dtrw=false
 -Dplusone.enableTest.baseline=true
 -Dplusone.enableTest.lsi=true
 -Dplusone.enableTest.plsi=false
 -Dplusone.enableTest.svdknn=false
 -Dplusone.enableTest.svdishknn=false
 -Dplusone.enableTest.heldOutPoissonLda=false
 -Dplusone.outPath=$out_dir
 -Dplusone.dumpMeta=false
 -Dplusone.randomSeed=9"

# options to sample cpu
# -agentlib:hprof=cpu=samples
# -agentlib:hprof=heap=sites

# options for memory
# -Xmx4096m

#java -agentlib:hprof=cpu=samples -Xmx4096m -cp Plusone.jar:lib/jars/ejml-0.17.jar $args plusone.Main
java -Xmx4096m -cp Plusone.jar:lib/jars/json.jar:lib/jars/ejml-0.17.jar:lib/jars/gson-1.7.1.jar:lib/colt-1.2.0.jar:lib/commons-lang-2.6.jar $args plusone.Main
